language: ruby
rvm:
- 2.3.3

script:
  - #set -e # halt script on error
  - uname -a
  - cat /etc/os-release
  - curl --version
  - ldd $(which curl)
  - dpkg -l | grep curl
  - ldd /home/travis/.rvm/rubies/ruby-2.3.3/bin/../lib/libruby.so.2.3
  - ldd /lib/x86_64-linux-gnu/libcrypt.so.1
  - bundle exec jekyll build
  - strace -f bundle exec htmlproofer ./_site 2>&1 | grep -i -e curl -e openssl -e gnutls
  - sudo apt-get install --quiet --yes libcurl4-openssl-dev
  - strace -f bundle exec htmlproofer ./_site 2>&1 | grep -i -e curl -e openssl -e gnutls
  - bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: true
